-- COPYRIGHT MATHIEU MULOT TZSR

test
DROP TABLE vente0;

CREATE TABLE vente0 (
  IDALBUM INT NOT NULL REFERENCES album(ID),
  MOIS INT NOT NULL CHECK (MOIS BETWEEN 1 AND 12),
  ANNEE INT NOT NULL CHECK (LEN(ANNEE)=4),
  NBVENTES INT NOT NULL CHECK (NBVENTES>0),
  PRIMARY KEY (IDALBUM,MOIS,ANNEE)
);

DROP TABLE vente1;

CREATE TABLE vente1 (
  ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  IDALBUM INT NOT NULL REFERENCES album(ID),
  MOIS INT NOT NULL CHECK (MOIS BETWEEN 1 AND 12),
  ANNEE INT NOT NULL CHECK (LEN(ANNEE)=4),
  NBVENTES INT NOT NULL CHECK (NBVENTES>0),
  UNIQUE (IDALBUM,MOIS,ANNEE)
);

DROP TABLE vente2;

CREATE TABLE vente2 (
  ID INT NOT NULL IDENTITY(1,1),
  IDALBUM INT NOT NULL,
  MOIS INT NOT NULL,
  ANNEE INT NOT NULL,
  NBVENTES INT NOT NULL,
  CONSTRAINT vente2_pk PRIMARY KEY(ID),
  CONSTRAINT vente2_fk FOREIGN KEY (IDALBUM) REFERENCES album(ID),
  CONSTRAINT vente2_mois_interval_ck CHECK (MOIS BETWEEN 1 AND 12),
  CONSTRAINT vente2_annee_length_ck CHECK (LEN(ANNEE)=4),
  CONSTRAINT vente2_nbventes_positif_ck CHECK (NBVENTES > 0),
  CONSTRAINT vente2_unique UNIQUE (IDALBUM,MOIS,ANNEE)
);


DROP TABLE vente3;

CREATE TABLE vente3 (
  ID INT NOT NULL IDENTITY(1,1),
  IDALBUM INT NOT NULL,
  MOIS INT NOT NULL,
  ANNEE INT NOT NULL,
  NBVENTES INT NOT NULL,
  CONSTRAINT vente3_pk PRIMARY KEY(ID)
);

ALTER TABLE vente3 ADD CONSTRAINT vente3_fk FOREIGN KEY (IDALBUM) REFERENCES album(ID);
ALTER TABLE vente3 ADD CONSTRAINT vente3_nbventes_positif CHECK (NBVENTES > 0);
ALTER TABLE vente3 ADD CONSTRAINT vente3_unique UNIQUE (IDALBUM,MOIS,ANNEE);

ALTER TABLE vente3 ADD JOUR_MOIS INT;
ALTER TABLE vente3 ALTER COLUMN JOUR_MOIS INT NOT NULL;
ALTER TABLE vente3 DROP COLUMN JOUR_MOIS;

ALTER TABLE vente3 DROP CONSTRAINT vente3_pk;
ALTER TABLE vente3 DROP CONSTRAINT vente3_nbventes_positif;

DROP TABLE vente4;

SELECT * INTO vente4
FROM VENTE;


test

-- Copie de tout ce qui se trouve dans le table vente vers la table vente4 (sans les contraintes)